### ISSUE TITLE
how to install and how to use

### ISSUE THREAD

**Issue by yh371174229** [gbif/maps#31]
is there a document that introduces how to install and how to use?

**Comment by MattBlissett** [comment]
Hi,

The API is documented at https://www.gbif.org/developer/maps .  If you wish to work with GBIF's data, I recommend using the API rather than trying to reprocess the data — it takes several hours on our Hadoop cluster to generate the pre-calculated tiles.

The only documentation about the backend system is the README files in this repository.  If you intend to reuse the code for some other purpose, I think you will need to make significant changes, and probably read+understand most of the code anyway.
